---

- name: "debug the value of the r_state"
  debug:
    var=r_state
  tags: [ 'debug' ]

# Install pre-request app for Ubuntu or Debian

## Install curl

- name: "Install curl"
  become: true
  apt: >
    name='{{ item }}'
    state='{{ r_state }}'
  with_items:
    - aptitude
  tags: [ 'packages', 'utilities' ]

## Install dirmngr

- name: "Install dirmngr"
  become: true
  apt: >
    name='{{ item }}'
    state='{{ r_state }}'
  with_items:
    - dirmngr
  when: ansible_distribution == 'Debian'

## run a dist upgrad just in case

- name: "apt-get dist-upgrade, keep old configs, use new config when no old config exists" 
  become: true
  apt:
    upgrade: 'dist'
    dpkg_options: 'force-confold,force-confdef'
  when: r_state == 'present' and r_dist_upgrade == true

## Install apt key for r packages

- name: "install apt-key for ubuntu R packages keyserver"
  become: true
  apt_key: >
    keyserver="hkp://keyserver.ubuntu.com:80"
    id="E084DAB9"
    state='{{ r_state }}'
  when: ansible_distribution == 'Ubuntu'

- name: "install apt-key for Debian R packages keyserver"
  become: true
  apt_key: >
    keyserver="hkp://keyserver.ubuntu.com:80"
    id="E19F5F87128899B192B1A2C2AD5F960A256A04AF"
    state='{{ r_state }}'
  when: ansible_distribution == 'Debian'


# Add specified repository to sources
#
# is this really idempotent?

#- name: "add cran_utstat_utoronto_ca_bin_linux_ubuntu to apt sources.d"
#  become: true
#  apt_repository:
#    mode: 0644
#    repo: deb http://cran.utstat.utoronto.ca/bin/linux/ubuntu  {{ ansible_distribution_release }}/
#    state: '{{ r_state }}'
#    update_cache: yes

- name: "add cran_rstudio_com_bin_linux_ubuntu to apt sources.d"
  become: true
  apt_repository:
    mode: 0644
    repo: 'deb https://cran.rstudio.com/bin/linux/ubuntu {{ ansible_distribution_release }}/'
    state: '{{ r_state }}'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' 

- name: "add cran_rstudio_com_bin_linux_Debian to apt sources.d"
  become: true
  apt_repository:
    mode: 0644
    repo: 'deb http://cran.rstudio.com/bin/linux/debian stretch-cran34/'
    state: '{{ r_state }}'
    update_cache: yes
  When:  ansible_distribution == 'Debian'

## install r base

- name: "Install (or remove) 'r-base'"
  become: true
  apt:
    update_cache: True
    name: '{{ item }}'
    state: '{{ r_state }}'
  with_items:
    - r-base
  tags: [ 'packages', 'utilities' ]

## install r base dev tools when desired

- name: "Install (or remove) 'r-base-dev'"
  become: true
  apt: >
    update_cache=True
    name='{{ item }}'
    state='{{ r_state }}'
  with_items:
    - r-base-dev
  when: r_dev_install == true
  tags: [ 'packages', 'utilities' ]

